# Generated by Django 2.1.7 on 2019-04-08 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=50)),
                ('property_address', models.CharField(max_length=200)),
                ('property_city', models.CharField(choices=[('New Delhi', 'New Delhi'), ('Noida', 'Noida'), ('Gurugram', 'Gurugram'), ('Chandigarh', 'Chandigarh'), ('Bangalore', 'Bangalore'), ('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Chennai', 'Chennai')], max_length=50)),
                ('property_state', models.CharField(choices=[('Delhi', 'Delhi'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Haryana', 'Haryana'), ('Punjab', 'Punjab'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Tamil Nadu', 'Tamil Nadu')], max_length=50)),
                ('property_pin', models.IntegerField()),
                ('property_price', models.IntegerField()),
                ('property_bedrooms', models.IntegerField()),
                ('property_bathrooms', models.IntegerField()),
                ('property_sqFeet', models.IntegerField()),
                ('property_lotSize', models.IntegerField()),
                ('property_garage', models.IntegerField()),
                ('property_listingDate', models.DateField(auto_now_add=True)),
                ('property_description', models.CharField(max_length=200)),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.ImageField(upload_to='property/')),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_name', to='properties.Property')),
            ],
        ),
    ]
