# Generated by Django 2.1.7 on 2019-04-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0006_auto_20190403_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_num',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
