# Generated by Django 2.1.7 on 2019-04-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0008_auto_20190404_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/profile_pic.jpeg', upload_to='media/user_profilePics/'),
        ),
    ]
