# Generated by Django 2.1.7 on 2019-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0009_auto_20190404_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='media/user_profilePics/'),
        ),
    ]
