# Generated by Django 2.1.7 on 2019-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0010_auto_20190404_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/profile_pic.jpeg', upload_to='user_profilePics/'),
        ),
    ]
